spring:
  mvc:
  #当出现 404 错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
    view:
      prefix: /WEB-INF/views/
  profiles:
    active: loc
  #resources:
  #不要为我们工程中的资源文件建立映射
    #add-mappings: false
